### ISSUE TITLE
incomplete property

### ISSUE THREAD

**Issue by scne** [spring-cloud-stream-app-starters/tensorflow#4]
After runing ```mvn package``` and adding result jar to dashboard I create my custom stream. I would set ```tensorflow.model``` and ```tensorflow.output-name``` but this isn't displayed on UI in dashboard

**Comment by artembilan** [comment]
Hi, @scne !

Sorry for delay, but anyway, please, let me to follow up with you what's going on and what maybe really wrong.
I do this:
1.
```
D:\SpringIO\spring-cloud-stream-app-starters\tensorflow>mvnw clean install -PgenerateApps
```
https://docs.spring.io/spring-cloud-stream-app-starters/docs/Bacon.RELEASE/reference/html/_introduction.html#_building_the_artifacts

2.
```
d:\SpringIO\spring-cloud-stream-app-starters\tensorflow\apps\tensorflow-processor-rabbit>mvnw package
```
Pay attention to the path, please.
3. Go to the Dashbord UI and register that Boot app as a process:
![image](https://user-images.githubusercontent.com/1071590/30445216-54f0dd7a-9953-11e7-9ea7-28a7757ea872.png)

4. Go to Streams tab and start a new stream definition:
![image](https://user-images.githubusercontent.com/1071590/30445607-87ad4662-9954-11e7-94dd-d4b8c4d3dbde.png)

where `tensorflow` properties look like:
![image](https://user-images.githubusercontent.com/1071590/30445637-a1f67ea8-9954-11e7-81d7-e9b49baa2858.png)


So, looks like everything works as expected!

Please, let us know what are we missing here.

(Issue will be closed in 48 hours without feedback)

**Comment by artembilan** [comment]
As I promised: closing with the answer above and lack of feedback from the reporter.

Feel free to reopen if you still have some concerns on the matter!

**Comment by scne** [comment]
Hi @artembilan 
trouble happens when I try to use spring-cloud-starter-stream-processor-twitter-sentiment as processor. i expected all properties which you shown above with more the vocabulary property. When I try to configure I see only Vocabulary and Label property

**Comment by artembilan** [comment]
Ok. Thank you for coming back...

I will try that one tomorrow as well.

**Comment by artembilan** [comment]
@scne ,

That's me again.
So, here is the result of the `twitter-sentiment-processor-rabbit-1.0.0.BUILD-SNAPSHOT.jar` application registration and its properties:

![image](https://user-images.githubusercontent.com/1071590/30823774-4db166e6-a1fb-11e7-8f0d-11a610731dbf.png)

To test this I use `Spring Cloud Data Flow Local Server  (v1.2.3.RELEASE)`.

I indeed see that we have properly configured `white-list`: https://github.com/spring-cloud-stream-app-starters/tensorflow/blob/master/spring-cloud-starter-stream-processor-twitter-sentiment/src/main/resources/META-INF/spring-configuration-metadata-whitelist.properties

So, not sure what's going on in your case...

**Comment by scne** [comment]
Hey @artembilan I solved few hours ago my trouble!! There is a mistake, I made a typo in my path when I created stream! Sorry

**Comment by artembilan** [comment]
😄 It happens! NP.

Please, come back to us for any other feedback in other issues.
