### ISSUE TITLE
ImageRecognitionOutputMessageBuilder.drawLabels causes java.lang.NoClassDefFoundError: Could not initialize class sun.font.SunFontManager

### ISSUE THREAD

**Issue by sstremler** [spring-cloud-stream-app-starters/tensorflow#40]
I use Spring Cloud Data Flow in an Azure Kubernetes Cluster and the image-recognition processor gives me [this](https://pastebin.com/H1avvbk7) exception.

The root cause is `java.lang.NoClassDefFoundError: Could not initialize class sun.font.SunFontManager` . The `drawLabels` method of `ImageRecognitionOutputMessageBuilder` calls the `getFontMetrics` method of `Graphics2D` which uses `SunFontManager`.

I installed the `libstdc++6` library on the Ubuntu VM, which was suggested as a workaround in some topics, but it didn't solve the issue. I read that since Java 6 `SunFontManager` is not part of the JDK.
https://stackoverflow.com/questions/9246371/java-binary-compatibility-issue-sun-font-fontmanager-class-became-interface

Is there a workaround?

**Comment by sabbyanandan** [comment]
Hi, @sstremler. Thank you for the report. Could you describe the app version in use and how have you attempted to use this application? The more the details, the better it would be to review and reason through what might be wrong in your setup.

**Comment by sstremler** [comment]
I use SCDF 2.3.0 installed with kubectl on Azure and image-recognition-processor docker:springcloudstream/image-recognition-processor-kafka:2.1.1.RELEASE.

Here is my pipeline:
`twitterstream --twitter.credentials.consumerKey=* --twitter.credentials.consumerSecret=* --twitter.credentials.accessToken=* --twitter.credentials.accessTokenSecret=* | splitter --expression=#jsonPath(payload,'$.entities.media[*].media_url') | httpclient --httpclient.httpMethod=GET --httpclient.urlExpression='new String(payload)' --httpclient.headersExpression={'Content-Type':'application/octet-stream'} --httpclient.expectedResponseType=byte[] | image-recognition | log`

If I add `--tensorflow.image.recognition.drawLabels=false` to the image-recognition app, it works well, but I'd like to try out this feature.

**Comment by sabbyanandan** [comment]
Thank you, that is the latest release — we will have a look.

**Comment by sstremler** [comment]
Getting a shell to the container with `kubectl` and installing `fontconfig` with `apt-get install fontconfig`, after I deployed the pod solved the problem.

The Java version in the container is:
```
# java -version
openjdk version "1.8.0_192"
OpenJDK Runtime Environment (build 1.8.0_192-b12)
OpenJDK 64-Bit Server VM (build 25.192-b12, mixed mode)
```

Can you add `fontconfig` to the docker image?

**Comment by tzolov** [comment]
Hi @sstremler,  thank you for spotting this problem!  Appreciate the effort of pining down the root cause of the issue. Following the tip, we've [updated](https://github.com/spring-cloud/openjdk-docker/commit/d86d63acef4057dac22513d8dae7c74ee3360390) our parent docker image to pre-install the missing `fontconfig` lib. As a result all https://dataflow.spring.io/Einstein-BUILD-SNAPSHOT-stream-applications-kafka-docker app images now include the library as well. 

Until the apps are released you can give the BS a try using those coordinates:
```
processor.image-recognition=docker:springcloudstream/image-recognition-processor-kafka:latest
processor.image-recognition.metadata=maven://org.springframework.cloud.stream.app:image-recognition-processor-kafka:jar:metadata:2.1.2.BUILD-SNAPSHOT
```

Also the https://github.com/spring-cloud/spring-cloud-skipper/issues/931 issue would fix the issue in cases of local docker-compose installations.

**Comment by sstremler** [comment]
Thanks @tzolov!
