### ISSUE TITLE
Upgrade tensorflow to 1.4.0

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud-stream-app-starters/tensorflow#6]
As a developer, I'd like to upgrade the [tensorflow-version](https://github.com/spring-cloud-stream-app-starters/tensorflow/blob/master/tensorflow-app-dependencies/pom.xml#L21) from 1.1.0 to 1.4.0.

**Comment by tzolov** [comment]
@sabbyanandan in #5 i upgraded to tenser-flow 1.3.0. Apparently 1.4.0 they have made some breaking API changes and it deserves more thoughtful work to upgrade to it. 
Shall I reopen this? or create a new one to track this requirement?

**Comment by sabbyanandan** [comment]
Oh, oops! I assumed it was already applied based on the conversation we have had in slack. I'll reopen it.
